### ISSUE TITLE
timm.data.resolve_model_data_config not available in version of timm posted in requirements

### ISSUE THREAD

**Issue by chrisjkuch** [line/Meta-AI-Video-Similarity-Challenge-3rd-Place-Solution#1]
https://github.com/line/Meta-AI-Video-Similarity-Challenge-3rd-Place-Solution/blob/38213200a6d9943bf26f9128ee68020cdf52e121/training/v46.py#L644

Here and other places, `AttributeError: module 'timm.data' has no attribute 'resolve_model_data_config'` is raised because this function is only available in future versions of `timm`, not `0.6.12` as specified in the requirements.

**Comment by lyakaap** [comment]
Thank you for pointing out the issues and sorry for bothering you...!
I fixed the problems including other issues you opened by recent commits. Please check.
