### ISSUE TITLE
Cannot download from provided DISC links

### ISSUE THREAD

**Issue by chrisjkuch** [line/Meta-AI-Video-Similarity-Challenge-3rd-Place-Solution#4]
https://github.com/line/Meta-AI-Video-Similarity-Challenge-3rd-Place-Solution/blob/c2a9be01e561940eb017ccfd48f53e732648591e/training/download_DISC21.sh#L6

To download the DISC dataset, users may first have to sign the dataset license agreement.

**Comment by lyakaap** [comment]
Fixed by this commit.
https://github.com/line/Meta-AI-Video-Similarity-Challenge-3rd-Place-Solution/commit/d319dd9faea3753d664d19ecbf19050e9a84cc35
