### ISSUE TITLE
"FFmpeg cannot edit existing files in-place" error during edit step

### ISSUE THREAD

**Issue by chrisjkuch** [line/Meta-AI-Video-Similarity-Challenge-3rd-Place-Solution#5]
https://github.com/line/Meta-AI-Video-Similarity-Challenge-3rd-Place-Solution/blob/c2a9be01e561940eb017ccfd48f53e732648591e/editing_prediction/video_generation_AugLy.py#L248

For many videos in the dataset, I am unable to use the selected `edit_method` because ffmpeg returns an error. I wrapped this in a try/catch to bypass

**Comment by PeifeiZhu** [comment]
I’m sorry that I forgot to mention this problem. When using AugLy functions `PerspectiveTransformAndShake` and `BlendVideos`, the above error appears randomly (it usually disappeared when we re-run the script even for the same sample). Other AugLy functions do not seem to have this problem.
We can solve it by try/catch or re-run but I still didn’t figure out the reason for this error.

I found other team also has this kind of random error when using AugLy.
https://github.com/WangWenhao0716/VSC-DescriptorTrack-Submission/tree/main/Training/Generate
